config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :coordinators
  root 'main#home'
  get 'main/home'
  get 'courses/index'
  #get 'contacts/new' => 'contacts#new'
  #post 'form' => 'contacts#create'
  resources :contacts
  resources :courses
  resources :coordinators
  resources :locations
  resources :categories

  unless Rails.application.config.consider_all_requests_local
    # having created corresponding controller and action
    match '/404' => 'errors#error_404', via: :all
    #get '/404' => 'errors#error_404', via: :get

  end

  get  '/signup',  to: 'coordinators#new'
  post '/signup',  to: 'coordinators#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'

  get '/upvote',   to: 'votes#new'
  get '/downvote', to: 'votes#new'
  post '/upvote',   to: 'votes#upvote'
  post '/downvote', to: 'votes#downvote'

  resources :courses do
      resources :votes
  end

  
  # match "*missing" => redirect("errors#error_404"), via: :all
end

app/models/coordinator.rb
class Coordinator < ApplicationRecord

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {minimum: 4}

  #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_EMAIL_REGEX = /\A[a-z]+\.[a-z]+@[rmit]+\.[edu]+\.+[au]+$\z/i
  validates :email, presence: true, length: {minimum: 4},
  format: { with: VALID_EMAIL_REGEX, message: 'Registration only open for RMIT Staff' },
  uniqueness: { case_sensitive: false } 

  has_secure_password
  has_many :courses, dependent: :destroy
  #attr_accessor :course_data
  validates :password, presence: true, length: {minimum: 8, message: 'Password must contain at least a lowercase letter, an uppercase letter, a digit, a special character and 8+ characters'} #,allow_nil: false

  has_many :votes, dependent: :destroy

  def Coordinator.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ?
      BCrypt::Engine::MIN_COST :                                     BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
  end



end

app/controllers/coordinators_controller.rb
class CoordinatorsController < ApplicationController
  before_action :logged_in_coordinator, only: [:index, :edit, :update, :destroy]
  before_action :correct_coordinator,   only: [:edit, :update]
  before_action :admin_coordinator,     only: [:create, :edit, :destroy]
  #before_action :set_coordinator, only: [:show, :edit, :update, :destroy]

  # GET /coordinators
  # GET /coordinators.json
  def index
    @coordinators = Coordinator.all
  end

  # GET /coordinators/1
  # GET /coordinators/1.json
  def show
  	@coordinator = Coordinator.find(params[:id])
  end

  # GET /coordinators/new
  def new
    @coordinator = Coordinator.new
  end

  # GET /coordinators/1/edit
  def edit
    @coordinator = Coordinator.find(params[:id])
  end

  # POST /coordinators
  # POST /coordinators.json
  def create
    @coordinator = Coordinator.new(coordinator_params)
      if @coordinator.save
        log_in @coordinator #remove this to force users to sign in again
        flash[:success] = "Account successfully created!"
       redirect_to @coordinator
      else
        render :new
      end

  end

  # PATCH/PUT /coordinators/1
  # PATCH/PUT /coordinators/1.json
  def update

    @coordinator = Coordinator.find(params[:id])
    if @coordinator.update_attributes(coordinator_params)
      flash[:success] = "Profile updated"
      redirect_to @coordinator
    else
      render 'edit'
    end

  end

  # DELETE /coordinators/1
  # DELETE /coordinators/1.json
  def destroy
    Coordinator.find(params[:id]).destroy
    flash[:success] = "Coordinator Account deleted"
    redirect_to coordinators_url

  end

  private

    def set_coordinator
      @coordinator = Coordinator.find(params[:id])
    end


    def coordinator_params
      # params.require(:coordinator).permit(:name, :image, :course_data => [])
      params.require(:coordinator).permit(:name, :email, :password,:password_confirmation,:course_data => [])
    end

    def admin_coordinator
      @coordinator = Coordinator.find_by(admin: true)
    end

    def correct_coordinator
      @coordinator = Coordinator.find(params[:id])
      redirect_to(root_url) unless current_coordinator?(@coordinator)|| current_coordinator.admin?
    end
end

app/helpers/coordinators_helper.rb
module CoordinatorsHelper
  def gravatar_for(coordinator, size: 100)
    gravatar_id = Digest::MD5::hexdigest(coordinator.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: coordinator.name, class: "gravatar")
    end
end

app/views/coordinators/_form.html.erb
<%= form_for(@coordinator) do |f| %>
  <%= render 'shared/error_messages', object: @coordinator %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/coordinators/edit.html.erb
<% provide(:title, 'Edit Profile') %>
<% provide(:button_text, 'Save') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @coordinator %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>
<button style="font-size: 20px"><%= link_to 'Return', coordinators_path %></button>

app/views/coordinators/index.html.erb
<% provide(:title, 'Coordinators') %>
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>Coordinators</h1>

  <% @coordinators.each do |coordinator| %>
  <div class="container">
    <%= gravatar_for coordinator %>
    <p><%= coordinator.name %></p>
    <div>
      <% if current_coordinator == coordinator && !current_coordinator.admin?%>
      <button><%= link_to 'Show Courses', coordinator %></button>  |
      <button><%= link_to 'Edit Coordinator', edit_coordinator_path(coordinator) %></button>
      <!-- <%= link_to 'Delete Coordinator', coordinator, method: :delete, data: { confirm: 'Are you sure?' } %> -->
      <% else %>
      <button><%= link_to 'Show Courses', coordinator %></button>
      <% end %>

      <% if current_coordinator.admin? && !current_coordinator?(@coordinator) %>
      <!-- <%= link_to 'Show Courses', coordinator %>  --> |
      <button><%= link_to 'Edit Coordinator', edit_coordinator_path(coordinator) %></button> |
      <button><%= link_to 'Delete Coordinator', coordinator, method: :delete, data: { confirm: 'Are you sure?' } %></button>
      <% end %>
    </div>

  </div><br>
  <% end %>
</div>

app/views/coordinators/new.html.erb
<!-- <h1>New Coordinator</h1>

<%= render 'form', coordinator: @coordinator %>

<%= link_to 'Back', main_home_url %> -->
<div class="container">
  <% provide(:title, 'Coordinator Register') %>
  <% provide(:button_text, 'Register') %>
  <h1>Coordinator Register</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    </div>
  </div>
</div>

app/views/coordinators/show.html.erb
<% provide(:title, @coordinator.name) %>
<div class="container">

  <div class="row">
    <div class="col-md-4">

      <p id="notice"><%= notice %></p>
      <p>
        <h3>Coordinator:</h3>
        <h4><%= @coordinator.name %></h4>
      </p>
      <p>
        <%= gravatar_for @coordinator %>
      </p>

    </div>
    <div class="col-md-8">
      <% if @coordinator.courses.any? %>
      <h3>Courses (<%= @coordinator.courses.count %>)</h3>
      <ol class="courses">
        <%= render @coordinator.courses %>
      </ol>
      <% end %>
    </div>
  </div><br><br>

  <% if current_coordinator == @coordinator %>
  <button><%= link_to 'Add New Course', new_course_path %></button> |
  <% end %>
  <button><%= link_to 'View Coordinators', coordinators_path %></button> |
  <button><%= link_to 'View Categories', categories_path %></button> |
  <button><%= link_to 'View Locations', locations_path %></button>
</div>