config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :coordinators
  root 'main#home'
  get 'main/home'
  get 'courses/index'
  #get 'contacts/new' => 'contacts#new'
  #post 'form' => 'contacts#create'
  resources :contacts
  resources :courses
  resources :coordinators
  resources :locations
  resources :categories

  unless Rails.application.config.consider_all_requests_local
    # having created corresponding controller and action
    match '/404' => 'errors#error_404', via: :all
    #get '/404' => 'errors#error_404', via: :get

  end

  get  '/signup',  to: 'coordinators#new'
  post '/signup',  to: 'coordinators#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'

  get '/upvote',   to: 'votes#new'
  get '/downvote', to: 'votes#new'
  post '/upvote',   to: 'votes#upvote'
  post '/downvote', to: 'votes#downvote'

  resources :courses do
      resources :votes
  end

  
  # match "*missing" => redirect("errors#error_404"), via: :all
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :courses
  #has_many :locations, through: :courses
  #validates :course_id, presence: true
  attr_accessor :course_id
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  

  def index
    @categories = Category.all
  end


  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new()
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
      if @category.save
        flash[:success] = "Category successfully added!"
       redirect_to categories_path
      else
        render :new
      end
  end

    def update
      @category = Category.find(params[:id])
        if @category.update_attributes(category_params)
          redirect_to categories_path
        else
          render 'edit'
        end
    end

    def destroy
      Category.find(params[:id]).destroy
      flash[:success] = "Category deleted"
      redirect_to categories_path

    end

  private
  def category_params
    params.require(:category).permit(:category, :course_ids)
  end

  def find_course
     @course = Course.find(params[:id])
     #@course = current_coordinator.courses.find(params[:id])
  end


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="container">
  <%= form_for @category do |f| %>
    <div class="field">
      <%= f.label :category %>
      <%= f.text_field :category %><br>
      <div class="btn-sub">
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<% if current_coordinator  %>
<h1>Editing Category</h1>
<% provide(:title, 'Edit Category') %>
<% provide(:button_text, 'Save') %>
<%= render 'form' %>
<button><%= link_to 'Return', categories_path %></button>
<% else %>
  <h1 style="color:red;"> Sorry not Allowed </h1>
  <h3 style="color:red;"> You are not allowed here!! Please go back </h3>
<% end %>

app/views/categories/index.html.erb
<% provide(:title, 'All Categories') %>
<% if current_coordinator  %>
<div class="container">

<% @categories.each do |category| %>
<ul><li>
<h3><%= category.category %></h3>

<button><%=link_to 'Edit Category', edit_category_path(category) %></button>
<button><%= link_to 'Delete Category', category, method: :delete, data: { confirm: 'Are you sure?' } %></button></li></ul>
<% end %>
</div><br><br>
<button><%= link_to 'Return', coordinator_path(current_coordinator) %></button>
<% else %>
  <h1 style="color:red;"> Sorry not Allowed </h1>
  <h3> You are not allowed here!! Please go back </h3>
<% end %>

app/views/categories/new.html.erb
<% if current_coordinator  %>
<h1>New Category</h1>
<% provide(:title, 'Create Category') %>
<% provide(:button_text, 'Create new category') %>
<%= render 'form' %>
<% else %>
<h1 style="color:red;"> Sorry not Allowed </h1>
<h3 style="color:red;"> You are not allowed here!! Please go back </h3>
<% end %>

app/views/categories/show.html.erb
<% provide(:title, @category.category) %>
<h3 style="text-align:center">Courses in: <%= @category.category %></h3><br>

<div class="container">
  <div class="row">
    <aside class="col-md-2">
      <% @category.courses.each do |course| %>
      <section class="logo">
        <%= image_tag(course.image.url)%>
      </section><br><br><br><br>
      <% end %>

    </aside>
    <div class="col-md-10">
      <% @category.courses.each do |cat| %>
      <section class="course">
        <p><strong>Name:</strong> <%= cat.name %></p>
        <p> <strong>Prerequisite:</strong> <%= cat.prerequisite %></p>
        <p><strong> Category:</strong> <%= @category.category %></p>
        <p><strong> Location:</strong> <% cat.locations.each do |c| %>
          <%= link_to c.location, location_path(c) %>&nbsp;&nbsp;
          <% end %> </p>

          <p><strong> Created:</strong> <%= time_ago_in_words(@category.created_at) %> ago</p>
          <i class="glyphicon glyphicon-thumbs-down" style="float:right"><%= cat.votes.downvote.count %></i>&nbsp;
          <i class="glyphicon glyphicon-thumbs-up" style="float:right"><%=cat.votes.upvote.count%></i>


          <% if current_coordinator %>
          <%= link_to raw('<span class="glyphicon glyphicon-thumbs-up"></span> like'), upvote_path(cat.id), method: :post %> &nbsp;
          <%= link_to raw('<span class="glyphicon glyphicon-thumbs-down"></span> disike'), downvote_path(cat.id), method: :post %>
          <br>

          <% if cat.coordinator_id == current_coordinator.id && !current_coordinator.admin?%>
          <button><%= link_to 'Edit Course', edit_course_path(cat) %></button>
          <% end %>

          <% if current_coordinator.admin?  %>
          <button><%=link_to 'Reset Votes', course_vote_path(cat), method: :delete, data: { confirm: 'Are you sure?' } %></button> |
          <button><%= link_to 'Edit Course', edit_course_path(cat) %></button> |
          <button><%= link_to 'Delete Course', cat, method: :delete, data: { confirm: 'Are you sure?' } %></button>
          <% end %>
          <% end %>

        </section><br>
        <% end %><br>

      </div><br>
    </div>
    <button ><%= link_to 'Return to Course List', courses_path %></button>
  </div>