config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :coordinators
  root 'main#home'
  get 'main/home'
  get 'courses/index'
  #get 'contacts/new' => 'contacts#new'
  #post 'form' => 'contacts#create'
  resources :contacts
  resources :courses
  resources :coordinators
  resources :locations
  resources :categories

  unless Rails.application.config.consider_all_requests_local
    # having created corresponding controller and action
    match '/404' => 'errors#error_404', via: :all
    #get '/404' => 'errors#error_404', via: :get

  end

  get  '/signup',  to: 'coordinators#new'
  post '/signup',  to: 'coordinators#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'

  get '/upvote',   to: 'votes#new'
  get '/downvote', to: 'votes#new'
  post '/upvote',   to: 'votes#upvote'
  post '/downvote', to: 'votes#downvote'

  resources :courses do
      resources :votes
  end

  
  # match "*missing" => redirect("errors#error_404"), via: :all
end

app/models/location.rb
class Location < ApplicationRecord
  has_and_belongs_to_many :courses
  #has_many :categories, through: :courses
  #validates :course_id, presence: true
  attr_accessor :course_id
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end


  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new()
  end

  def edit
    @location = Location.find(params[:id])
  end

  def create
    @location = Location.new(location_params)
      if @location.save
        flash[:success] = "Location successfully added!"
       redirect_to locations_path
      else
        render :new
      end
  end

    def update
      @location = Location.find(params[:id])
        if @location.update_attributes(location_params)
          redirect_to locations_path
        else
          render 'edit'
        end
    end

    def destroy
      Location.find(params[:id]).destroy
      flash[:success] = "Location deleted"
      redirect_to locations_path
    end

  private
  def location_params
    params.require(:location).permit(:location, :course_ids)
  end

  def find_course
     @course = Course.find(params[:id])
     #@course = current_coordinator.courses.find(params[:id])
  end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<div class="container">
  <%= form_for @location do |f| %>
    <div class="field">
      <%= f.label :location %>
      <%= f.text_field :location %><br>
      <div class="btn-sub">
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/locations/edit.html.erb
<% if current_coordinator  %>
<h1>Editing Location</h1>
<% provide(:title, 'Edit Location') %>
<% provide(:button_text, 'Save') %>
<%= render 'form' %>
<button><%= link_to 'Return', locations_path %></button>
<% else %>
  <h1 style="color:red;"> Sorry not Allowed </h1>
  <h3 style="color:red;"> You are not allowed here!! Please go back </h3>
<% end %>

app/views/locations/index.html.erb
<% provide(:title, 'All Locations') %>
<% if current_coordinator  %>
<div class="container">

<h3> Click on a Location to edit info </h3>
<% @locations.each do |location| %>
<ul><li>
<h3><%= location.location %></h3>
<button><%=link_to 'Edit Location', edit_location_path(location) %></button>
<button><%= link_to 'Delete Location', location, method: :delete, data: { confirm: 'Are you sure?' } %></button></li></ul>
<% end %>


</div>
<button><%= link_to 'Return', coordinator_path(current_coordinator) %></button>
<% else %>
  <h1 style="color:red;"> Sorry not Allowed </h1>
  <h3> You are not allowed here!! Please go back </h3>
<% end %>

app/views/locations/new.html.erb
<% if current_coordinator  %>
<h1>New Location</h1>
<% provide(:title, 'Create Location') %>
<% provide(:button_text, 'Create new location') %>
<%= render 'form' %>
<% else %>
<h1 style="color:red;"> Sorry not Allowed </h1>
<h3 style="color:red;"> You are not allowed here!! Please go back </h3>
<% end %>

app/views/locations/show.html.erb
<% provide(:title, @location.location) %>
<h3 style="text-align:center">Courses scheduled in location: <%= @location.location %></h3><br>
<div class="container">
  <div class="container">
    <div class="row">
      <aside class="col-md-2">
        <% @location.courses.each do |course| %>
        <section class="logo">
          <%= image_tag(course.image.url)%>
        </section><br><br><br><br>
        <% end %>

      </aside>
      <div class="col-md-10">
        <% @location.courses.each do |loco| %>
        <div class="course">
          <p><strong> Name:</strong> <%= loco.name %></p>
          <p><strong> Prerequisite:</strong> <%= loco.prerequisite %></p>
          <p><strong> Category:</strong> <% loco.categories.each do |c| %>
            <%= link_to c.category , category_path(c) %>&nbsp;&nbsp;
            <% end %> </p>
            <!-- <p>Category: <%= link_to loco.categories.map(&:category).join, category_path %></p> -->
            <p><strong>Location:</strong> <%= @location.location %></p>
            <p><strong> Created:</strong> <%= time_ago_in_words(@location.created_at) %> ago</p>
            <i class="glyphicon glyphicon-thumbs-down" style="float:right"><%=loco.votes.downvote.count%></i>
            &nbsp;
            <i class="glyphicon glyphicon-thumbs-up" style="float:right"><%=loco.votes.upvote.count%></i>

            <% if current_coordinator  %>
            <%= link_to raw('<span class="glyphicon glyphicon-thumbs-up"></span> like'), upvote_path(loco.id), method: :post %> &nbsp;&nbsp;
            <%= link_to raw('<span class="glyphicon glyphicon-thumbs-down"></span> disike'), downvote_path(loco.id), method: :post %><br>

            <% if loco.coordinator_id == current_coordinator.id && !current_coordinator.admin?%>
            <button><%= link_to 'Edit Course', edit_course_path(loco) %></button>
            <% end %>

            <% if current_coordinator.admin?  %>
            <button><%=link_to 'Reset Votes', course_vote_path(loco), method: :delete, data: { confirm: 'Are you sure?' } %></button> |
            <button><%= link_to 'Edit Course', edit_course_path(loco) %></button> |
            <button><%= link_to 'Delete Course', loco, method: :delete, data: { confirm: 'Are you sure?' } %></button>
            <% end %>
            <% end %>


          </div><br>
          <% end %><br>

        </div><br>
      </div>
      <button ><%= link_to 'Return to Course List', courses_path %></button>
    </div>