config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :coordinators
  root 'main#home'
  get 'main/home'
  get 'courses/index'
  #get 'contacts/new' => 'contacts#new'
  #post 'form' => 'contacts#create'
  resources :contacts
  resources :courses
  resources :coordinators
  resources :locations
  resources :categories

  unless Rails.application.config.consider_all_requests_local
    # having created corresponding controller and action
    match '/404' => 'errors#error_404', via: :all
    #get '/404' => 'errors#error_404', via: :get

  end

  get  '/signup',  to: 'coordinators#new'
  post '/signup',  to: 'coordinators#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'

  get '/upvote',   to: 'votes#new'
  get '/downvote', to: 'votes#new'
  post '/upvote',   to: 'votes#upvote'
  post '/downvote', to: 'votes#downvote'

  resources :courses do
      resources :votes
  end

  
  # match "*missing" => redirect("errors#error_404"), via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :courses
  #has_many :locations, through: :courses
  #validates :course_id, presence: true
  attr_accessor :course_id
end

app/models/contact.rb
class Contact
  include ActiveModel::Model
  attr_accessor :name, :email, :phone, :content
  validates :name, :phone, :content, presence: true
  validates :email, :presence => :true,
  :format => { :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
    :message => "must be a valid email address"
    }

end

app/models/coordinator.rb
class Coordinator < ApplicationRecord

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {minimum: 4}

  #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_EMAIL_REGEX = /\A[a-z]+\.[a-z]+@[rmit]+\.[edu]+\.+[au]+$\z/i
  validates :email, presence: true, length: {minimum: 4},
  format: { with: VALID_EMAIL_REGEX, message: 'Registration only open for RMIT Staff' },
  uniqueness: { case_sensitive: false } 

  has_secure_password
  has_many :courses, dependent: :destroy
  #attr_accessor :course_data
  validates :password, presence: true, length: {minimum: 8, message: 'Password must contain at least a lowercase letter, an uppercase letter, a digit, a special character and 8+ characters'} #,allow_nil: false

  has_many :votes, dependent: :destroy

  def Coordinator.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ?
      BCrypt::Engine::MIN_COST :                                     BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
  end



end

app/models/course.rb
class Course < ApplicationRecord

  mount_uploader :image, CourseUploader
  belongs_to :coordinator

  validates :name, presence: true, length: {minimum: 10}
  validates :prerequisite, presence: true, length: {minimum: 10}
  validates :description, presence: true, length: {minimum: 30}


  validates :coordinator_id, presence: true
  has_many :votes, dependent: :destroy
  has_and_belongs_to_many :locations
  has_and_belongs_to_many :categories



end

app/models/location.rb
class Location < ApplicationRecord
  has_and_belongs_to_many :courses
  #has_many :categories, through: :courses
  #validates :course_id, presence: true
  attr_accessor :course_id
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :course
  belongs_to :coordinator
  enum vote_type: [ :upvote, :downvote ]
  validates_uniqueness_of :course_id, scope: :coordinator_id


  def count_like
    self.votes.where(vote_type: 0).size
  end

  def count_dislike
    self.votes.where(vote_type: 1).size
  end


end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

  def error_404
      render 'errors/not_found'
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home

  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
#before_action :find_course
skip_before_action :verify_authenticity_token


    def create

    end

    def upvote
      @course = Course.find(params[:format])

        #flash[:success] = "Happy you like the course :)!"
        if current_coordinator.votes.where(:course_id => @course).present?
          flash[:danger] = "You can only vote once per course!"
          #redirect_to(course_path(@course))
          redirect_back(fallback_location: courses_path)
        else
          @course.votes.upvote.build(coordinator_id: current_coordinator.id)
          @course.save
          flash[:success] = "Thanks for your vote!"
          #redirect_to(course_path(@course))
          redirect_back(fallback_location: courses_path)

        end
    end

    def downvote
        @course = Course.find(params[:format])

        if current_coordinator.votes.where(:course_id => @course).present?
          flash[:danger] = "You can only vote once per course!"
          #redirect_to(course_path(@course))
          redirect_back(fallback_location: courses_path)
        else
         @course.votes.downvote.create(coordinator_id: current_coordinator.id)
         @course.save
         flash[:success] = "Thanks for your vote!"
         #redirect_to(course_path(@course))
         redirect_back(fallback_location: courses_path)
        end

    end


    def destroy
      @course = Course.find(params[:course_id])
      @course.votes.destroy_all
      flash[:success] = "Votes Resetted"
      #redirect_to courses_path
      redirect_back(fallback_location: courses_path)

    end

    private
    def find_course
       @course = Course.find(params[:id])
    end

    def vote_params
     params.require(:vote).permit(:coordinator_id, :course_id, :vote_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/coordinators_helper.rb
module CoordinatorsHelper
  def gravatar_for(coordinator, size: 100)
    gravatar_id = Digest::MD5::hexdigest(coordinator.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: coordinator.name, class: "gravatar")
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(coordinator)
    session[:coordinator_id] = coordinator.id
  end

  def current_coordinator?(coordinator)
    coordinator == current_coordinator
  end


  def current_coordinator
    if session[:coordinator_id]
      @current_coordinator ||= Coordinator.find_by(id: session[:coordinator_id])
    end
  end

  def logged_in?
    !current_coordinator.nil?
  end

  def log_out
    session.delete(:coordinator_id)
    @current_coordinator = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/votes_helper.rb
module VotesHelper

end

app/views/layouts/_footer.html.erb
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
<footer class="footer">
  <div class="footer-bottom">
			<div class="container">
				<div class="row">
					<ul class="pull-left"> <p>Contact Us</p>
            <li><%= link_to 'Contact us for more details', "/contacts/new" %></li>
            <li>Tel: 012345678</li>
            <li>Fax: 098765432</li>
            <li>Email: stage.1@rmit.edu.au</li>
          </ul>
          <ul class="pull-left"> <p>General Inquiries</p>
            <li><a  href="#">Andy Song</a></li>
            <li><a  href="#">JunLang Jian</a></li>
            <li><a  href="#">Ali</a></li>
          </ul>
          <ul class="pull-left"> <p>Useful Links</p>
            <li><a  href="#">RMIT Course</a></li>
            <li><a  href="#">RMIT Help Desk</a></li>
            <li><a  href="#">RMIT International</a></li>
          </ul>
					<ul class="pull-left"> <p>Media</p>
            <li><a href="#" class="link"><span class="fa fa-youtube"></span>YouTube</a></li>
            <li><a href="#" class="link"><span class="fa fa-youtube"></span>Facebook</a></li>
            <li><a href="#" class="link"><i class="fa fa-instagram"></i>Instagram</a></li>
            <li><a href="#" class="link"><i class="fa fa-twitter"></i>Twitter</a></li>

            <!-- <li><a target="_blank" href="#">Twitter</a></li>
            <li><a target="_blank" href="#">Skype</a></li> -->
          </ul>
				</div>
			</div>
		</div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar">
  <% if logged_in? %>
    <%= link_to 'Home', courses_path %>
  <% else %>
    <%= link_to 'Home', "/main/home" %>
  <% end %>

  <div class="dropdown">

    <% if logged_in? %>
    <!-- <li><%= link_to "Coordinators", '#' %></li> -->
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span>
        <%= current_coordinator.name %> <b class="caret"></b>
      </a>
      <div class="dropdown-content">
        <%= link_to "View Profile", current_coordinator %>
        <%= link_to "Edit Profile", edit_coordinator_path(current_coordinator) %>
        <%= link_to "Log out", logout_path, method: :delete %>
      </div>
    </li>
    <% else %>
  <%= link_to raw('<span class="glyphicon glyphicon-user"></span> Log in') , login_path %>
  <% end %>
</div>

<div class="dropdown">
  <button class="dropbtn"><span class="glyphicon glyphicon-map-marker"></span> Location
    <span class="caret"></span>
  </button>

  <div class="dropdown-content">

    <% Location.all.group(:id).each do |course| %>
      <%= link_to course.location, location_path(course.id) %>
    <% end %>
    <% if logged_in? %>
    <%= link_to "Create Location", new_location_path %>
    <% end %>
  </div>

</div>

<div class="dropdown">
  <button class="dropbtn"><span class="glyphicon glyphicon-screenshot"></span> Category
    <span class="caret"></span>
  </button>

  <div class="dropdown-content">
    <% Category.all.group(:id).each do |course| %>
    <%= link_to course.category, category_path(course.id) %>
    <% end %>
    <% if logged_in? %>
    <%= link_to "Create Category", new_category_path %>
    <% end %>
  </div>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=yield(:title)%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_404.html.erb
<div class="container">
  <p> Sorry not found </p>
</div>

app/views/shared/_error_contacts.html.erb
<% if @contact.errors.any? %>
  <div id="error_explanation">
    <!-- <div class="alert alert-danger">
      The form contains <%= pluralize(@contact.errors.count, "error") %>.
    </div> -->
    <ul>
      <p> Please correct the following errors: </p>
    <% @contact.errors.full_messages.each do |msg| %>

      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_courses.html.erb
<% if @course.errors.any? %>
  <div id="error_explanation">
    <!-- <div class="alert alert-danger">
      The form contains <%= pluralize(@course.errors.count, "error") %>.
    </div> -->
    <ul>
      <p> Please correct the following errors: </p>
    <% @course.errors.full_messages.each do |msg| %>

      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @coordinator.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@coordinator.errors.count, "error") %>.
    </div>
    <ul>
      <p> Please correct the following errors: </p>
    <% @coordinator.errors.full_messages.each do |msg| %>

      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>